# .yml content
name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # ec2-13-232-238-134.ap-south-1.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }} # ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }} # beta_key.pem (select the whole content in the file)
          script: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install fastapi uvicorn
            cd ./Server-test # change directory to your working repo
            pip install -r requirements.txt
            git pull origin main
            sudo killall uvicorn # kills all uvicorn services
            pm2 restart 0 # 0 is the id of pm2 running in server
